{ config, pkgs, ... }:

{
  imports =
    [
      # Adds my packages to the scope of this file.
      ./overlays
      # This file was generated by the installation and refers to specific hardware on the machine
      /etc/nixos/hardware-configuration.nix
      ./nixos/fonts.nix
      ./nixos/users.nix
      # ./nixos/virtualbox.nix
      ./nixos/vmware.nix
    ];

  networking.hostName = "nixos";

  time.timeZone = "America/Los_Angeles";

  nixpkgs.config.allowUnfree = true;
  environment.systemPackages = pkgs.callPackage ./installList/linuxSystem.nix { };

  environment.etc = (
    {}
    // pkgs.myFiles.etc.hosts
    // pkgs.myFiles.etc.ssh_config
    // pkgs.myFiles.etc.trulia_server
    // pkgs.myFiles.etc.trulia_api_local
  );

  # Hardware
  hardware.pulseaudio.enable = true;
  hardware.pulseaudio.zeroconf.publish.enable = true;
  hardware.pulseaudio.tcp = {
    enable = true;
    anonymousClients.allowedIpRanges = [
      "127.0.0.1"
    ];
  };

  # Security
  security.initialRootPassword = "$6$G4kaf6Pg.Q$baOttdistuWWJoUF0kcxgQbRpyIkJ/5vKMS7P33EOkgQvT4da8rRjsaKQ8d.h7xrblNK5Ne5jmzUc.k7z18XS1";

  # Sudo
  security.sudo.wheelNeedsPassword = false;

  # List services that you want to enable:

  # Enable the Mopidy Music Server.
  services.mopidy = with pkgs.appConfigs.mopidy; {
    inherit extensionPackages;
    inherit configuration;
    enable = false;
  };

  # Enable the NTP daemon.
  services.ntp.enable = true;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # Enable the Offline IMAP daemon.
  # services.offlineimap.enable = true;

  # Enable CUPS to print documents.
  # services.printing.enable = true;

  # Enable the X11 windowing system.
  services.xserver.enable = true;

  # Cron Jobs
  services.cron.enable = true;
  services.cron.systemCronJobs = [
    pkgs.myCronJobs.hourlySyncProjects
  ];

  # Enable the i3 Window Manager through auto-logging in tdoggett
  services.xserver.displayManager.auto = {
    enable = true;
    user = "tdoggett";
  };

  # The NixOS release to be compatible with for stateful data such as databases.
  system.nixos.stateVersion = "18.03";
}
